services:
  pixtures:
    image: pixtures:latest
    container_name: pixtures
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}  # Use variables from .env
      PRINTFUL_BEARER: ${PRINTFUL_BEARER}  # Use variables from .env
      MONGO_USERNAME: ${MONGO_USERNAME}  # Use variables from .env
      MONGO_PASSWORD: ${MONGO_PASSWORD}  # Use variables from .env
      MONGO_HOST: ${MONGO_HOST}  # Use variables from .env
      APP_PORT: ${APP_PORT}  # Use variables from .env
      HOST: ${HOST}  # Use variables from .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb
    networks:
      - pixtures
  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    networks:
      - pixtures
    environment:
      VUE_APP_BACKEND_URL: ${VUE_APP_BACKEND_URL}  # Use variables from .env
      VUE_APP_GOOGLE_MAPS_API_KEY: ${VUE_APP_GOOGLE_MAPS_API_KEY}
      VUE_APP_GOOGLE_MAP_ID: ${VUE_APP_GOOGLE_MAP_ID}
      VUE_APP_SNIPCARD_API_KEY: ${VUE_APP_SNIPCARD_API_KEY}
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}  # Use variables from .env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}  # Use variables from .env
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - pixtures

volumes:
  mongo_data:
networks:
  pixtures:
    name: pixtures
    driver: bridge