services:
  pixtures:
    image: pixtures:latest
    container_name: ${ENVIRONMENT}-pixtures
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SELF_DOMAIN: ${SELF_DOMAIN}
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
      PRINTFUL_BEARER: ${PRINTFUL_BEARER}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST} 
      APP_PORT: ${APP_PORT}
      HOST: ${HOST}  # Use variables from .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb
    networks:
      - pixtures
  pixtures-frontend:
    image: pixtures-frontend:latest
    container_name: ${ENVIRONMENT}-pixtures-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_BACKEND_URL: ${VUE_APP_BACKEND_URL}  # Use variables from .env
        VUE_APP_GOOGLE_MAPS_API_KEY: ${VUE_APP_GOOGLE_MAPS_API_KEY}
        VUE_APP_GOOGLE_MAP_ID: ${VUE_APP_GOOGLE_MAP_ID}
        VUE_APP_SNIPCARD_API_KEY: ${VUE_APP_SNIPCARD_API_KEY}
        VUE_APP_PORT: ${VUE_APP_PORT}
    ports:
      - "${VUE_APP_PORT}:${VUE_APP_PORT}"
    networks:
      - pixtures
  mongodb:
    image: mongo:latest
    container_name: ${ENVIRONMENT}-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}  # Use variables from .env
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}  # Use variables from .env
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - pixtures

volumes:
  mongo_data:
networks:
  pixtures:
    name: pixtures
    driver: bridge